/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_user_interface (void);
GtkWidget* create_delete_warning (void);
GtkWidget* create_logout (void);
GtkWidget* create_invoice (void);
GtkWidget* create_confirm_edit (void);
GtkWidget* create_addwindow (void);
GtkWidget* create_login (void);
GtkWidget* create_welcome (void);
GtkWidget* create_AdminwindowLogin (void);
GtkWidget* create_AdminwindowParkConfig (void);
GtkWidget* create_AdminwindowMain (void);
GtkWidget* create_AdminwindowNewAcc (void);
