/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include "interface.h"
#include "support.h"

int main(int argc, char *argv[]) {
    GtkWidget *main_window;
    

#ifdef ENABLE_NLS
    bindtextdomain(GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
    bind_textdomain_codeset(GETTEXT_PACKAGE, "UTF-8");
    textdomain(GETTEXT_PACKAGE);
#endif

    gtk_set_locale();
    gtk_init(&argc, &argv);

    // Load the Glade interface
    GtkBuilder *builder = gtk_builder_new();
    gtk_builder_add_from_file(builder, "../my_glade_file.glade", NULL);  // Adjust path if needed

    // Set up the main window
    main_window = GTK_WIDGET(gtk_builder_get_object(builder, "main_window"));
    gtk_widget_show_all(main_window);

   

    gtk_main();
    return 0;
}

