/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *label9;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label10;
  GtkWidget *radiobutton3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label12;
  GtkWidget *radiobutton2;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label14;
  GtkWidget *radiobutton5;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label15;
  GtkWidget *label8;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *label21;
  GtkWidget *radiobutton4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label13;
  GtkWidget *ooo;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label22;
  GtkWidget *clist1;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label5;
  GtkWidget *label38;
  GtkWidget *hseparator3;
  GtkWidget *hseparator1;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *combo_entry1;
  GtkWidget *label1;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport2;
  GtkWidget *fixed3;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *image11;
  GtkWidget *label46;
  GtkWidget *button3;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label47;
  GtkWidget *clist2;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label62;
  GtkWidget *hseparator4;
  GtkWidget *label2;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport3;
  GtkWidget *fixed4;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *label58;
  GtkWidget *label57;
  GtkWidget *entry13;
  GtkWidget *label59;
  GtkWidget *hseparator5;
  GtkWidget *hseparator6;
  GtkWidget *hseparator7;
  GtkWidget *label61;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label60;
  GtkWidget *image13;
  GtkWidget *button4;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label63;
  GtkWidget *combo2;
  GList *combo2_items = NULL;
  GtkWidget *combo_entry2;
  GtkWidget *clist3;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *image15;
  GtkWidget *label70;
  GtkWidget *label3;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 16, 136);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 272, 136);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 16, 240);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label9 = gtk_label_new (_("selectionner un mode du lavage"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 0, 304);
  gtk_widget_set_size_request (label9, 240, 32);

  radiobutton1 = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1, 8, 344);
  gtk_widget_set_size_request (radiobutton1, 140, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (radiobutton1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_(" Lavage \303\240 la main"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox1), label10, FALSE, FALSE, 0);

  radiobutton3 = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton3, 8, 408);
  gtk_widget_set_size_request (radiobutton3, 192, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (radiobutton3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Lavage en profondeur"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);

  radiobutton2 = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2, 8, 376);
  gtk_widget_set_size_request (radiobutton2, 208, 40);
  gtk_container_set_border_width (GTK_CONTAINER (radiobutton2), 1);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (radiobutton2), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("lavage automatique"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox5), label14, FALSE, FALSE, 0);

  radiobutton5 = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton5, 8, 472);
  gtk_widget_set_size_request (radiobutton5, 168, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (radiobutton5), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Lavage \303\251cologique"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox6), label15, FALSE, FALSE, 0);

  label8 = gtk_label_new (_("Matricule du voiture :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 0, 208);
  gtk_widget_set_size_request (label8, 176, 16);

  label7 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 256, 104);
  gtk_widget_set_size_request (label7, 96, 17);

  label6 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 8, 104);
  gtk_widget_set_size_request (label6, 64, 16);

  label21 = gtk_label_new (_("Type de voiture :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed1), label21, 248, 208);
  gtk_widget_set_size_request (label21, 160, 16);

  radiobutton4 = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton4, 8, 440);
  gtk_widget_set_size_request (radiobutton4, 200, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (radiobutton4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_(" Lavage \303\240 domicile"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox4), label13, FALSE, FALSE, 0);

  ooo = gtk_button_new ();
  gtk_widget_show (ooo);
  gtk_fixed_put (GTK_FIXED (fixed1), ooo, 144, 552);
  gtk_widget_set_size_request (ooo, 128, 61);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ooo), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Payer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox7), label22, FALSE, FALSE, 0);

  clist1 = gtk_clist_new (6);
  gtk_widget_show (clist1);
  gtk_fixed_put (GTK_FIXED (fixed1), clist1, 632, 88);
  gtk_widget_set_size_request (clist1, 920, 592);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 171);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 146);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 206);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label32 = gtk_label_new (_("No. du commonde"));
  gtk_widget_show (label32);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label32);

  label33 = gtk_label_new (_("Nom Prenom"));
  gtk_widget_show (label33);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label33);

  label34 = gtk_label_new (_("Voiture"));
  gtk_widget_show (label34);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label34);

  label35 = gtk_label_new (_("Matriqule"));
  gtk_widget_show (label35);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, label35);

  label36 = gtk_label_new (_("Date du commonde"));
  gtk_widget_show (label36);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, label36);

  label37 = gtk_label_new (_("Prix Totale"));
  gtk_widget_show (label37);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 5, label37);

  label5 = gtk_label_new (_("ajouter un demonde :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 104, 40);
  gtk_widget_set_size_request (label5, 224, 32);

  label38 = gtk_label_new (_("Historie du demande"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed1), label38, 800, 0);
  gtk_widget_set_size_request (label38, 592, 72);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator3, 16, 520);
  gtk_widget_set_size_request (hseparator3, 512, 16);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 16, 80);
  gtk_widget_set_size_request (hseparator1, 512, 16);

  label16 = gtk_label_new (_(": 15 dt"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed1), label16, 160, 344);
  gtk_widget_set_size_request (label16, 49, 40);

  label17 = gtk_label_new (_(": 20 dt"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed1), label17, 184, 376);
  gtk_widget_set_size_request (label17, 49, 40);

  label18 = gtk_label_new (_(": 80 dt"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed1), label18, 200, 408);
  gtk_widget_set_size_request (label18, 49, 40);

  label19 = gtk_label_new (_(": 40 dt"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed1), label19, 176, 440);
  gtk_widget_set_size_request (label19, 49, 40);

  label20 = gtk_label_new (_(": 60 dt"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed1), label20, 176, 472);
  gtk_widget_set_size_request (label20, 49, 40);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed1), combo1, 272, 240);
  gtk_widget_set_size_request (combo1, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo1), TRUE);
  combo1_items = g_list_append (combo1_items, (gpointer) _("<vide>"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("Voiture Normale"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("Sumi"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("Partnaire"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_show (combo_entry1);
  gtk_entry_set_text (GTK_ENTRY (combo_entry1), _("<vide>"));
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry1), 8226);

  label1 = gtk_label_new (_("Service lavage"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (viewport2), fixed3);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8, 48, 72);
  gtk_widget_set_size_request (entry8, 208, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed3), entry9, 48, 160);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 56, 264);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label44 = gtk_label_new (_("Nom Prenom :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed3), label44, 32, 32);
  gtk_widget_set_size_request (label44, 128, 40);

  label45 = gtk_label_new (_("Matriqule :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed3), label45, 16, 128);
  gtk_widget_set_size_request (label45, 144, 40);

  image11 = create_pixmap (window1, "images (1).jpeg");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed3), image11, 280, 32);
  gtk_widget_set_size_request (image11, 240, 264);

  label46 = gtk_label_new (_("No. d'heurs : (note: 1dt par 1h)"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed3), label46, 48, 216);
  gtk_widget_set_size_request (label46, 224, 48);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 40, 312);
  gtk_widget_set_size_request (button3, 256, 64);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button3), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Payer: (+5dt pour la reservation)"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox8), label47, FALSE, FALSE, 0);

  clist2 = gtk_clist_new (6);
  gtk_widget_show (clist2);
  gtk_fixed_put (GTK_FIXED (fixed3), clist2, 16, 536);
  gtk_widget_set_size_request (clist2, 688, 240);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 0, 51);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 1, 111);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 2, 87);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 3, 107);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 4, 113);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist2));

  label48 = gtk_label_new (_("No."));
  gtk_widget_show (label48);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 0, label48);

  label49 = gtk_label_new (_("Nom Prenom"));
  gtk_widget_show (label49);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 1, label49);

  label50 = gtk_label_new (_("Matriqule"));
  gtk_widget_show (label50);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 2, label50);

  label51 = gtk_label_new (_("No. d'heures"));
  gtk_widget_show (label51);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 3, label51);

  label52 = gtk_label_new (_("date"));
  gtk_widget_show (label52);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 4, label52);

  label53 = gtk_label_new (_("prix totale"));
  gtk_widget_show (label53);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 5, label53);

  label54 = gtk_label_new (_("Historie d'affichage"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed3), label54, 208, 472);
  gtk_widget_set_size_request (label54, 240, 56);

  label62 = gtk_label_new (_("Ajouter une reservation"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed3), label62, 152, 0);
  gtk_widget_set_size_request (label62, 240, 24);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator4, 24, 400);
  gtk_widget_set_size_request (hseparator4, 672, 40);

  label2 = gtk_label_new (_("Service reservation"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (viewport3), fixed4);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed4), entry10, 24, 128);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed4), entry11, 224, 128);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 24, 232);
  gtk_widget_set_size_request (entry12, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  label58 = gtk_label_new (_("Type de vehicule:"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed4), label58, 0, 288);
  gtk_widget_set_size_request (label58, 176, 40);

  label57 = gtk_label_new (_("Numero du telephone:"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed4), label57, 8, 192);
  gtk_widget_set_size_request (label57, 192, 40);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed4), entry13, 272, 232);
  gtk_widget_set_size_request (entry13, 112, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  label59 = gtk_label_new (_("Matriqule de voiture:"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed4), label59, 256, 192);
  gtk_widget_set_size_request (label59, 176, 40);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator5, 0, 80);
  gtk_widget_set_size_request (hseparator5, 448, 16);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator6, 0, 384);
  gtk_widget_set_size_request (hseparator6, 448, 16);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator7, 0, 448);
  gtk_widget_set_size_request (hseparator7, 448, 16);

  label61 = gtk_label_new (_("Numero du notre service du remorcage romorcheur :  20 548 745 / 98 358 452"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed4), label61, 0, 416);
  gtk_widget_set_size_request (label61, 536, 16);

  label55 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed4), label55, 24, 96);
  gtk_widget_set_size_request (label55, 49, 40);

  label56 = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed4), label56, 216, 96);
  gtk_widget_set_size_request (label56, 72, 40);

  label60 = gtk_label_new (_("DEMONDE DU REPAIRE"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed4), label60, 8, 32);
  gtk_widget_set_size_request (label60, 200, 40);

  image13 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed4), image13, 192, 32);
  gtk_widget_set_size_request (image13, 40, 32);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 296, 320);
  gtk_widget_set_size_request (button4, 120, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button4), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("payer"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox9), label63, FALSE, FALSE, 0);

  combo2 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo2)->popwin),
                     "GladeParentKey", combo2);
  gtk_widget_show (combo2);
  gtk_fixed_put (GTK_FIXED (fixed4), combo2, 24, 328);
  gtk_widget_set_size_request (combo2, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo2), TRUE);
  combo2_items = g_list_append (combo2_items, (gpointer) _("<vide>"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Mecanique"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Electrique"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo2), combo2_items);
  g_list_free (combo2_items);

  combo_entry2 = GTK_COMBO (combo2)->entry;
  gtk_widget_show (combo_entry2);
  gtk_entry_set_text (GTK_ENTRY (combo_entry2), _("<vide>"));
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry2), 8226);

  clist3 = gtk_clist_new (6);
  gtk_widget_show (clist3);
  gtk_fixed_put (GTK_FIXED (fixed4), clist3, 80, 544);
  gtk_widget_set_size_request (clist3, 680, 320);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 4, 153);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 5, 121);
  gtk_clist_column_titles_show (GTK_CLIST (clist3));

  label64 = gtk_label_new (_("No."));
  gtk_widget_show (label64);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 0, label64);

  label65 = gtk_label_new (_("Matriqule"));
  gtk_widget_show (label65);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 1, label65);

  label66 = gtk_label_new (_("Date debut"));
  gtk_widget_show (label66);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 2, label66);

  label67 = gtk_label_new (_("date fin"));
  gtk_widget_show (label67);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 3, label67);

  label68 = gtk_label_new (_("etat du reperation\n           (A,C,T)"));
  gtk_widget_show (label68);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 4, label68);

  label69 = gtk_label_new (_("Prix Totale"));
  gtk_widget_show (label69);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 5, label69);

  image15 = create_pixmap (window1, "png-clipart-car-tow-truck-towing-vehicle-impoundment-car-service-car-thumbnail.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed4), image15, 464, 24);
  gtk_widget_set_size_request (image15, 352, 357);

  label70 = gtk_label_new (_("HISTOIRE"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed4), label70, 368, 512);
  gtk_widget_set_size_request (label70, 120, 16);

  label3 = gtk_label_new (_("servise du reperation"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (window1, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, ooo, "ooo");
  GLADE_HOOKUP_OBJECT (window1, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, clist1, "clist1");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (window1, combo_entry1, "combo_entry1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window1, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window1, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, label45, "label45");
  GLADE_HOOKUP_OBJECT (window1, image11, "image11");
  GLADE_HOOKUP_OBJECT (window1, label46, "label46");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, clist2, "clist2");
  GLADE_HOOKUP_OBJECT (window1, label48, "label48");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");
  GLADE_HOOKUP_OBJECT (window1, label50, "label50");
  GLADE_HOOKUP_OBJECT (window1, label51, "label51");
  GLADE_HOOKUP_OBJECT (window1, label52, "label52");
  GLADE_HOOKUP_OBJECT (window1, label53, "label53");
  GLADE_HOOKUP_OBJECT (window1, label54, "label54");
  GLADE_HOOKUP_OBJECT (window1, label62, "label62");
  GLADE_HOOKUP_OBJECT (window1, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window1, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window1, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window1, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (window1, label58, "label58");
  GLADE_HOOKUP_OBJECT (window1, label57, "label57");
  GLADE_HOOKUP_OBJECT (window1, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (window1, label59, "label59");
  GLADE_HOOKUP_OBJECT (window1, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (window1, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (window1, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (window1, label61, "label61");
  GLADE_HOOKUP_OBJECT (window1, label55, "label55");
  GLADE_HOOKUP_OBJECT (window1, label56, "label56");
  GLADE_HOOKUP_OBJECT (window1, label60, "label60");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label63, "label63");
  GLADE_HOOKUP_OBJECT (window1, combo2, "combo2");
  GLADE_HOOKUP_OBJECT (window1, combo_entry2, "combo_entry2");
  GLADE_HOOKUP_OBJECT (window1, clist3, "clist3");
  GLADE_HOOKUP_OBJECT (window1, label64, "label64");
  GLADE_HOOKUP_OBJECT (window1, label65, "label65");
  GLADE_HOOKUP_OBJECT (window1, label66, "label66");
  GLADE_HOOKUP_OBJECT (window1, label67, "label67");
  GLADE_HOOKUP_OBJECT (window1, label68, "label68");
  GLADE_HOOKUP_OBJECT (window1, label69, "label69");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, label70, "label70");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *label39;
  GtkWidget *image8;
  GtkWidget *image9;
  GtkWidget *image10;
  GtkWidget *label40;
  GtkWidget *entry4;
  GtkWidget *label41;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label43;
  GtkWidget *label42;
  GtkWidget *button2;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  label39 = gtk_label_new (_("Payer en ligne"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed2), label39, 0, 32);
  gtk_widget_set_size_request (label39, 192, 32);

  image8 = create_pixmap (window2, "images.png");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed2), image8, 16, 72);
  gtk_widget_set_size_request (image8, 176, 128);

  image9 = create_pixmap (window2, "images (1).png");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed2), image9, 200, 72);
  gtk_widget_set_size_request (image9, 272, 128);

  image10 = create_pixmap (window2, "images.jpeg");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed2), image10, 480, 72);
  gtk_widget_set_size_request (image10, 224, 128);

  label40 = gtk_label_new (_("Nom sur la carte"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed2), label40, 136, 272);
  gtk_widget_set_size_request (label40, 144, 25);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 152, 320);
  gtk_widget_set_size_request (entry4, 392, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label41 = gtk_label_new (_("Numero de carte"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed2), label41, 144, 392);
  gtk_widget_set_size_request (label41, 136, 25);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 152, 440);
  gtk_widget_set_size_request (entry5, 392, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry6, 152, 568);
  gtk_widget_set_size_request (entry6, 192, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed2), entry7, 352, 568);
  gtk_widget_set_size_request (entry7, 192, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label43 = gtk_label_new (_("cryptogramme visuelle"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed2), label43, 312, 512);
  gtk_widget_set_size_request (label43, 232, 33);

  label42 = gtk_label_new (_("Date d expiration"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed2), label42, 104, 512);
  gtk_widget_set_size_request (label42, 216, 33);

  button2 = gtk_button_new_with_mnemonic (_("PAYER"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 264, 640);
  gtk_widget_set_size_request (button2, 176, 45);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, label39, "label39");
  GLADE_HOOKUP_OBJECT (window2, image8, "image8");
  GLADE_HOOKUP_OBJECT (window2, image9, "image9");
  GLADE_HOOKUP_OBJECT (window2, image10, "image10");
  GLADE_HOOKUP_OBJECT (window2, label40, "label40");
  GLADE_HOOKUP_OBJECT (window2, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window2, label41, "label41");
  GLADE_HOOKUP_OBJECT (window2, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window2, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window2, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window2, label43, "label43");
  GLADE_HOOKUP_OBJECT (window2, label42, "label42");
  GLADE_HOOKUP_OBJECT (window2, button2, "button2");

  return window2;
}

