/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create__Avis_et_R__clamations (void)
{
  GtkWidget *_Avis_et_R__clamations;
  GtkWidget *alignment1;
  GtkWidget *fixed1;
  GtkWidget *fixed11;
  GtkWidget *hseparator1;
  GtkWidget *image9;
  GtkWidget *label2;
  GtkWidget *treeview1;
  GtkWidget *notebook2;
  GtkWidget *fixed2;
  GtkWidget *entry_nomparking_ajout_vis;
  GtkWidget *entry_commentaire_avis;
  GtkWidget *entry_user_ajout_avis;
  GtkWidget *label20;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *button_ajout_avis;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label555;
  GtkWidget *label15;
  GtkWidget *entry26;
  GtkWidget *label62;
  GtkWidget *label12;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *entry25;
  GtkWidget *label43;
  GtkWidget *fixed3;
  GtkWidget *entry_modif_avis;
  GtkWidget *entry_reclamation_modif;
  GtkWidget *entry_nomparking_modif_avis;
  GtkWidget *entry_user_modif_avis;
  GtkWidget *button_modif_avis;
  GtkWidget *alignment4;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label57;
  GtkWidget *label21;
  GtkWidget *label17;
  GtkWidget *label63;
  GtkWidget *label19;
  GtkWidget *label18;
  GtkWidget *label16;
  GtkWidget *combo2;
  GList *combo2_items = NULL;
  GtkWidget *entry890;
  GtkWidget *label44;
  GtkWidget *fixed4;
  GtkWidget *entry_user_supprim_avis;
  GtkWidget *entry_nomparking_supprim_avis;
  GtkWidget *button_supprim;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label54;
  GtkWidget *label24;
  GtkWidget *label23;
  GtkWidget *label22;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *label64;
  GtkWidget *radiobutton3;
  GtkWidget *label66;
  GtkWidget *label65;
  GtkWidget *radiobutton4;
  GtkWidget *label99;
  GtkWidget *fixed8;
  GtkWidget *entry_nomparking_detail;
  GtkWidget *fixed10;
  GtkWidget *label37;
  GtkWidget *button_view_detail;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label56;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview1;
  GtkWidget *label40;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview2;
  GtkWidget *label41;
  GtkWidget *scrolledwindow4;
  GtkWidget *textview3;
  GtkWidget *label42;
  GtkWidget *label36;
  GtkWidget *D__tails_de_Parking;
  GtkWidget *fixed14;
  GtkWidget *label180;

  _Avis_et_R__clamations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (_Avis_et_R__clamations), _("window1"));

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (_Avis_et_R__clamations), alignment1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (alignment1), fixed1);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed11, 992, 72);
  gtk_widget_set_size_request (fixed11, 50, 50);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 904, 16);
  gtk_widget_set_size_request (hseparator1, 56, 40);

  image9 = create_pixmap (_Avis_et_R__clamations, "bubble_feedback_enquete_BSB_2019 (2).png");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed1), image9, 912, 0);
  gtk_widget_set_size_request (image9, 144, 88);

  label2 = gtk_label_new (_(" Avis et R\303\251clamations"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 400, 40);
  gtk_widget_set_size_request (label2, 208, 17);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 608, 88);
  gtk_widget_set_size_request (treeview1, 448, 392);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook2, 16, 88);
  gtk_widget_set_size_request (notebook2, 592, 392);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook2), GTK_POS_RIGHT);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed2);

  entry_nomparking_ajout_vis = gtk_entry_new ();
  gtk_widget_show (entry_nomparking_ajout_vis);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nomparking_ajout_vis, 128, 128);
  gtk_widget_set_size_request (entry_nomparking_ajout_vis, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomparking_ajout_vis), 8226);

  entry_commentaire_avis = gtk_entry_new ();
  gtk_widget_show (entry_commentaire_avis);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_commentaire_avis, 128, 240);
  gtk_widget_set_size_request (entry_commentaire_avis, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_commentaire_avis), 8226);

  entry_user_ajout_avis = gtk_entry_new ();
  gtk_widget_show (entry_user_ajout_avis);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_user_ajout_avis, 128, 64);
  gtk_widget_set_size_request (entry_user_ajout_avis, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_user_ajout_avis), 8226);

  label20 = gtk_label_new (_("User ID"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed2), label20, 24, 72);
  gtk_widget_set_size_request (label20, 89, 16);

  label13 = gtk_label_new (_("Parking ID"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 0, 136);
  gtk_widget_set_size_request (label13, 128, 16);

  label14 = gtk_label_new (_("Rate"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 0, 192);
  gtk_widget_set_size_request (label14, 120, 24);

  button_ajout_avis = gtk_button_new ();
  gtk_widget_show (button_ajout_avis);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajout_avis, 144, 328);
  gtk_widget_set_size_request (button_ajout_avis, 120, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_ajout_avis), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label555 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label555);
  gtk_box_pack_start (GTK_BOX (hbox1), label555, FALSE, FALSE, 0);

  label15 = gtk_label_new (_("Avis"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 8, 248);
  gtk_widget_set_size_request (label15, 112, 17);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed2), entry26, 128, 288);
  gtk_widget_set_size_request (entry26, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  label62 = gtk_label_new (_("Reclamation"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed2), label62, 16, 296);
  gtk_widget_set_size_request (label62, 104, 16);

  label12 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 120, 16);
  gtk_widget_set_size_request (label12, 176, 16);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed2), combo1, 128, 192);
  gtk_widget_set_size_request (combo1, 160, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo1), TRUE);
  combo1_items = g_list_append (combo1_items, (gpointer) _("1 Star"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("2 Star"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("3 Star"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("4 Star"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("5 Star"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  entry25 = GTK_COMBO (combo1)->entry;
  gtk_widget_show (entry25);
  gtk_widget_set_size_request (entry25, -1, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  label43 = gtk_label_new (_("Ajouter "));
  gtk_widget_show (label43);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label43);
  gtk_widget_set_size_request (label43, 184, 44);
  gtk_misc_set_alignment (GTK_MISC (label43), 0.5, 0.47);
  gtk_misc_set_padding (GTK_MISC (label43), 0, 3);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed3);

  entry_modif_avis = gtk_entry_new ();
  gtk_widget_show (entry_modif_avis);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_modif_avis, 136, 224);
  gtk_widget_set_size_request (entry_modif_avis, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_avis), 8226);

  entry_reclamation_modif = gtk_entry_new ();
  gtk_widget_show (entry_reclamation_modif);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_reclamation_modif, 136, 280);
  gtk_widget_set_size_request (entry_reclamation_modif, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_reclamation_modif), 8226);

  entry_nomparking_modif_avis = gtk_entry_new ();
  gtk_widget_show (entry_nomparking_modif_avis);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_nomparking_modif_avis, 136, 112);
  gtk_widget_set_size_request (entry_nomparking_modif_avis, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomparking_modif_avis), 8226);

  entry_user_modif_avis = gtk_entry_new ();
  gtk_widget_show (entry_user_modif_avis);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_user_modif_avis, 136, 56);
  gtk_widget_set_size_request (entry_user_modif_avis, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_user_modif_avis), 8226);

  button_modif_avis = gtk_button_new ();
  gtk_widget_show (button_modif_avis);
  gtk_fixed_put (GTK_FIXED (fixed3), button_modif_avis, 152, 336);
  gtk_widget_set_size_request (button_modif_avis, 112, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_modif_avis), alignment4);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label57 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox3), label57, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label57, -1, 28);

  label21 = gtk_label_new (_("User ID"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 40, 64);
  gtk_widget_set_size_request (label21, 49, 17);

  label17 = gtk_label_new (_("Parking ID"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 0, 120);
  gtk_widget_set_size_request (label17, 128, 16);

  label63 = gtk_label_new (_("Avis"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed3), label63, 40, 232);
  gtk_widget_set_size_request (label63, 49, 17);

  label19 = gtk_label_new (_("Reclamation"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 0, 288);
  gtk_widget_set_size_request (label19, 136, 16);

  label18 = gtk_label_new (_(" Rate"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 16, 176);
  gtk_widget_set_size_request (label18, 88, 16);

  label16 = gtk_label_new (_("Modifier "));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 128, 16);
  gtk_widget_set_size_request (label16, 176, 16);
  gtk_misc_set_alignment (GTK_MISC (label16), 0.5, 0.47);

  combo2 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo2)->popwin),
                     "GladeParentKey", combo2);
  gtk_widget_show (combo2);
  gtk_fixed_put (GTK_FIXED (fixed3), combo2, 136, 168);
  gtk_widget_set_size_request (combo2, 160, 32);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo2), TRUE);
  combo2_items = g_list_append (combo2_items, (gpointer) _("1 Star"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("2 Star"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("3 Star"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("4 Star"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("5 Star"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo2), combo2_items);
  g_list_free (combo2_items);

  entry890 = GTK_COMBO (combo2)->entry;
  gtk_widget_show (entry890);
  gtk_widget_set_size_request (entry890, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry890), 8226);

  label44 = gtk_label_new (_("Modifier "));
  gtk_widget_show (label44);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label44);
  gtk_widget_set_size_request (label44, 160, 32);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed4);

  entry_user_supprim_avis = gtk_entry_new ();
  gtk_widget_show (entry_user_supprim_avis);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_user_supprim_avis, 128, 104);
  gtk_widget_set_size_request (entry_user_supprim_avis, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_user_supprim_avis), 8226);

  entry_nomparking_supprim_avis = gtk_entry_new ();
  gtk_widget_show (entry_nomparking_supprim_avis);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_nomparking_supprim_avis, 128, 192);
  gtk_widget_set_size_request (entry_nomparking_supprim_avis, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomparking_supprim_avis), 8226);

  button_supprim = gtk_button_new ();
  gtk_widget_show (button_supprim);
  gtk_fixed_put (GTK_FIXED (fixed4), button_supprim, 144, 320);
  gtk_widget_set_size_request (button_supprim, 104, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_supprim), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox5), label54, FALSE, FALSE, 0);

  label24 = gtk_label_new (_("Parking ID"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 0, 200);
  gtk_widget_set_size_request (label24, 128, 16);

  label23 = gtk_label_new (_("User ID"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 0, 112);
  gtk_widget_set_size_request (label23, 144, 16);

  label22 = gtk_label_new (_("Supprimer "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 136, 32);
  gtk_widget_set_size_request (label22, 144, 24);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton2, 112, 280);
  gtk_widget_set_size_request (radiobutton2, 24, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  label64 = gtk_label_new (_("Avis"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed4), label64, 96, 256);
  gtk_widget_set_size_request (label64, 49, 17);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton3, 264, 280);
  gtk_widget_set_size_request (radiobutton3, 32, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label66 = gtk_label_new (_("both"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed4), label66, 256, 256);
  gtk_widget_set_size_request (label66, 49, 17);

  label65 = gtk_label_new (_("Reclamation"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed4), label65, 160, 256);
  gtk_widget_set_size_request (label65, 88, 16);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton4, 192, 280);
  gtk_widget_set_size_request (radiobutton4, 40, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  label99 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label99);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label99);
  gtk_widget_set_size_request (label99, -1, 44);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed8);

  entry_nomparking_detail = gtk_entry_new ();
  gtk_widget_show (entry_nomparking_detail);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_nomparking_detail, 120, 64);
  gtk_widget_set_size_request (entry_nomparking_detail, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomparking_detail), 8226);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed8), fixed10, 40, 288);
  gtk_widget_set_size_request (fixed10, 50, 50);

  label37 = gtk_label_new (_("Nom du Parking"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed8), label37, 0, 64);
  gtk_widget_set_size_request (label37, 120, 17);

  button_view_detail = gtk_button_new ();
  gtk_widget_show (button_view_detail);
  gtk_fixed_put (GTK_FIXED (fixed8), button_view_detail, 136, 104);
  gtk_widget_set_size_request (button_view_detail, 74, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_view_detail), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("View"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox7), label56, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed8), notebook1, 32, 144);
  gtk_widget_set_size_request (notebook1, 304, 128);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview1);

  label40 = gtk_label_new (_("Note moyenne"));
  gtk_widget_show (label40);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label40);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview2);

  label41 = gtk_label_new (_("Avis"));
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label41);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow4);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  textview3 = gtk_text_view_new ();
  gtk_widget_show (textview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), textview3);

  label42 = gtk_label_new (_(" R\303\251clamation"));
  gtk_widget_show (label42);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label42);

  label36 = gtk_label_new (_("D\303\251tails du Parking"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed8), label36, 120, 16);
  gtk_widget_set_size_request (label36, 136, 17);

  D__tails_de_Parking = gtk_fixed_new ();
  gtk_widget_show (D__tails_de_Parking);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), D__tails_de_Parking);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_fixed_put (GTK_FIXED (D__tails_de_Parking), fixed14, 8, 8);
  gtk_widget_set_size_request (fixed14, 80, 32);

  label180 = gtk_label_new (_("D\303\251tails du Parking"));
  gtk_widget_show (label180);
  gtk_fixed_put (GTK_FIXED (D__tails_de_Parking), label180, 0, 0);
  gtk_widget_set_size_request (label180, 184, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (_Avis_et_R__clamations, _Avis_et_R__clamations, "_Avis_et_R__clamations");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, image9, "image9");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label2, "label2");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_nomparking_ajout_vis, "entry_nomparking_ajout_vis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_commentaire_avis, "entry_commentaire_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_user_ajout_avis, "entry_user_ajout_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label20, "label20");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label13, "label13");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label14, "label14");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, button_ajout_avis, "button_ajout_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, image1, "image1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label555, "label555");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label15, "label15");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label62, "label62");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label12, "label12");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label43, "label43");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_modif_avis, "entry_modif_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_reclamation_modif, "entry_reclamation_modif");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_nomparking_modif_avis, "entry_nomparking_modif_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_user_modif_avis, "entry_user_modif_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, button_modif_avis, "button_modif_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, image3, "image3");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label57, "label57");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label21, "label21");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label17, "label17");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label63, "label63");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label19, "label19");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label18, "label18");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label16, "label16");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, combo2, "combo2");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry890, "entry890");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label44, "label44");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_user_supprim_avis, "entry_user_supprim_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_nomparking_supprim_avis, "entry_nomparking_supprim_avis");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, button_supprim, "button_supprim");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, image5, "image5");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label54, "label54");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label24, "label24");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label23, "label23");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label22, "label22");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label64, "label64");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label66, "label66");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label65, "label65");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label99, "label99");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, entry_nomparking_detail, "entry_nomparking_detail");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label37, "label37");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, button_view_detail, "button_view_detail");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, image7, "image7");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label56, "label56");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label40, "label40");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label41, "label41");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, textview3, "textview3");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label42, "label42");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label36, "label36");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, D__tails_de_Parking, "D__tails_de_Parking");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (_Avis_et_R__clamations, label180, "label180");

  return _Avis_et_R__clamations;
}

GtkWidget*
create_dialogue (void)
{
  GtkWidget *dialogue;
  GtkWidget *fixed12;
  GtkWidget *button20;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image10;
  GtkWidget *label60;
  GtkWidget *label59;
  GtkWidget *image12;
  GtkWidget *button21;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image11;
  GtkWidget *label61;

  dialogue = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (dialogue), _("window2"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (dialogue), fixed12);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed12), button20, 72, 240);
  gtk_widget_set_size_request (button20, 74, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button20), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image10 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox8), image10, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Yes"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox8), label60, FALSE, FALSE, 0);

  label59 = gtk_label_new (_("ARE YOU SURE ?"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed12), label59, 112, 160);
  gtk_widget_set_size_request (label59, 168, 24);

  image12 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed12), image12, 160, 80);
  gtk_widget_set_size_request (image12, 64, 56);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed12), button21, 248, 240);
  gtk_widget_set_size_request (button21, 88, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button21), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image11 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox9), image11, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("CANCEL"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox9), label61, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialogue, dialogue, "dialogue");
  GLADE_HOOKUP_OBJECT (dialogue, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (dialogue, button20, "button20");
  GLADE_HOOKUP_OBJECT (dialogue, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (dialogue, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (dialogue, image10, "image10");
  GLADE_HOOKUP_OBJECT (dialogue, label60, "label60");
  GLADE_HOOKUP_OBJECT (dialogue, label59, "label59");
  GLADE_HOOKUP_OBJECT (dialogue, image12, "image12");
  GLADE_HOOKUP_OBJECT (dialogue, button21, "button21");
  GLADE_HOOKUP_OBJECT (dialogue, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (dialogue, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (dialogue, image11, "image11");
  GLADE_HOOKUP_OBJECT (dialogue, label61, "label61");

  return dialogue;
}

